import telebot
from telebot import types

TOKEN = '5731681878:AAENAmnmNfzigC6Fh8XuCEIclj21EFfT8vA'
bot = telebot.TeleBot(TOKEN)


@bot.message_handler(commands=['start'])
def start(message):
    markup3 = types.InlineKeyboardMarkup(row_width=2)
    btn1 = types.InlineKeyboardButton('Альбомдар', callback_data='Альбомдар')
    btn2 = types.InlineKeyboardButton('Жанрлар', callback_data='Жанрлар')
    btn3 = types.InlineKeyboardButton('Орындаушылар', callback_data='Орындаушылар')
    btn4 = types.InlineKeyboardButton('Басқалары', callback_data='Басқалары')
    btn5 = types.InlineKeyboardButton('Жаңалықтар', callback_data='Жаңалықтар')
    markup3.add(btn1, btn2, btn3, btn4, btn5)
    photo = open('unnamed.jpg', 'rb')
    bot.send_photo(message.chat.id, photo, f"Добро пожаловать!, {message.from_user.first_name} {message.from_user.last_name}!\n ! ", reply_markup=markup3)


@bot.callback_query_handler(func=lambda call: True)
def callback(call):
    if call.message:
        if call.data == 'Альбомдар':
            markup3 = types.InlineKeyboardMarkup(row_width=2)
            btn1 = types.InlineKeyboardButton('Лучшие', callback_data='Лучшие')
            btn2 = types.InlineKeyboardButton('Топы', callback_data='Топы')
            btn3 = types.InlineKeyboardButton('В машину', callback_data='В машину')
            btn4 = types.InlineKeyboardButton('Утро', callback_data='Утро')
            btn5 = types.InlineKeyboardButton('Отдых', callback_data='Отдых')
            btn6 = types.InlineKeyboardButton('Ремиксы', callback_data='Ремиксы')
            markup3.add(btn1, btn2, btn3, btn4, btn5, btn6)
            photo = open('Rad.jpg', 'rb')
            bot.send_photo(call.message.chat.id, photo, 'Альбомдар', reply_markup=markup3)
        if call.data == 'Лучшие':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Подробнее", url="https://mp3party.net/pop-music"))
            ms = 'Слушайте популярные и лучшие песни здесь!'
            uu = open('Maneskin - Beggin.mp3', 'rb')
            up = open('ITZY - Cheshire.mp3', 'rb')
            un = open('RM - Lonely.mp3', 'rb')
            um = open('Ирина Кайратовна - 5000.mp3', 'rb')
            uo = open('Skillet - Psycho In My Head.mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_audio(call.message.chat.id, um)
            bot.send_audio(call.message.chat.id, uo)
            bot.send_message(call.message.chat.id, ms, reply_markup=btn1)
        if call.data == 'Топы':
            ms = 'Топы Ноября'
            ma = '5'
            mc = '4'
            md = '3'
            mv = '2'
            me = '1'

            uu = open('Imagine Dragons - thunder.mp3', 'rb')
            up = open('Элджей - ZEF.mp3', 'rb')
            un = open('PharaoH - На Луне.mp3', 'rb')
            um = open('Roberto Cacciapaglia - Oceano.mp3', 'rb')
            uo = open('Скриптонит - Положение.mp3', 'rb')
            bot.send_message(call.message.chat.id, ms)
            bot.send_message(call.message.chat.id, ma)
            bot.send_audio(call.message.chat.id, uu)
            bot.send_message(call.message.chat.id, mc)
            bot.send_audio(call.message.chat.id, up)
            bot.send_message(call.message.chat.id, md)
            bot.send_audio(call.message.chat.id, un)
            bot.send_message(call.message.chat.id, mv)
            bot.send_audio(call.message.chat.id, um)
            bot.send_message(call.message.chat.id, me)
            bot.send_audio(call.message.chat.id, uo)
        if call.data == 'В машину':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Подробнее", url="https://mp3party.net/trip-music"))
            ms = 'Музыка на дорогу'
            uu = open('Скриптонит - Положение.mp3', 'rb')
            up = open('Flo Rida - apple bottom jeans.mp3', 'rb')
            un = open('Unknown - She share story.mp3', 'rb')
            um = open('FILV - BALENCIAGA.mp3', 'rb')
            uo = open('Hippie Sabotage - Devil Eyes.mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_audio(call.message.chat.id, um)
            bot.send_audio(call.message.chat.id, uo)
            bot.send_message(call.message.chat.id, ms, reply_markup=btn1)
        if call.data == 'Утро':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Подробнее", url="https://mp3party.net/collection/c%20%D0%B4%D0%BE%D0%B1%D1%80%D1%8B%D0%BC%20%D1%83%D1%82%D1%80%D0%BE%D0%BC?sort=pop"))
            ms = 'Утро'
            uu = open('Imagine Dragons - Whatever It Takes.mp3', 'rb')
            up = open('Imagine Dragons - Its Time.mp3', 'rb')
            un = open('David Guetta Feat. Ne-Yo & Akon - Play Hard.mp3', 'rb')
            um = open('Halsey - Bad At Love.mp3', 'rb')
            uo = open('Bruno Mars - The Lazy Song.mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_audio(call.message.chat.id, um)
            bot.send_audio(call.message.chat.id, uo)
            bot.send_message(call.message.chat.id, ms, reply_markup=btn1)
        if call.data == 'Отдых':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Подробнее", url="https://mp3party.net/genres/spokoynoe?sort=pop"))
            ms = 'Отдых'
            uu = open('Roderic ft. Jacqueline Jones - Passengers.mp3', 'rb')
            up = open('Mr.Kitty - After Dark.mp3', 'rb')
            un = open('Cloves - Dont forget about me.mp3', 'rb')
            um = open('Conan Gray - Heather.mp3', 'rb')
            uo = open('Unknown - She share story.mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_audio(call.message.chat.id, um)
            bot.send_audio(call.message.chat.id, uo)
            bot.send_message(call.message.chat.id, ms, reply_markup=btn1)
        if call.data == 'Ремиксы':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Подробнее", url="https://mp3party.net/genres/remix?sort=pop"))
            ms = 'Ремиксы'
            uu = open('Seeya - Chocolata.mp3', 'rb')
            up = open('Serhat Durmus - La Clin (Dabro Remix).mp3', 'rb')
            un = open('Alexandra Stan - Boy Oh Boy.mp3', 'rb')
            um = open('Morandi - Kalinka.mp3', 'rb')
            uo = open('Jaymes Young - Infinity (Desrym Remix).mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_audio(call.message.chat.id, um)
            bot.send_audio(call.message.chat.id, uo)
            bot.send_message(call.message.chat.id, ms, reply_markup=btn1)
        if call.data == 'Жанрлар':
            markup3 = types.InlineKeyboardMarkup(row_width=2)
            btn1 = types.InlineKeyboardButton('Классика', callback_data='Классика')
            btn2 = types.InlineKeyboardButton('Рок', callback_data='Рок')
            btn3 = types.InlineKeyboardButton('Электронная', callback_data='Электронная')
            btn4 = types.InlineKeyboardButton('Поп', callback_data='Поп')
            btn5 = types.InlineKeyboardButton('Шансон', callback_data='Шансон')
            btn6 = types.InlineKeyboardButton('Казахстан', callback_data='Казахстан')
            markup3.add(btn1, btn2, btn3, btn4, btn5, btn6)
            photo = open('Rad.jpg', 'rb')
            bot.send_photo(call.message.chat.id, photo, 'Жанрлар', reply_markup=markup3)
        if call.data == 'Классика':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Подробнее", url="https://mp3party.net/genres/classic"))
            ms = 'Классика'
            uu = open('Roderic ft. Jacqueline Jones - Passengers.mp3', 'rb')
            up = open('Royksopp - Here She Comes Again.mp3', 'rb')
            un = open('Offenbach - Can Can Music.mp3', 'rb')
            um = open('Space - Running In The City.mp3', 'rb')
            uo = open('Roberto Cacciapaglia - Oceano.mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_audio(call.message.chat.id, um)
            bot.send_audio(call.message.chat.id, uo)
            bot.send_message(call.message.chat.id, ms, reply_markup=btn1)
        if call.data == 'Рок':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Подробнее", url="https://mp3party.net/genres/rock"))
            ms = 'Рок'
            uu = open('Imagine Dragons - believer.mp3', 'rb')
            up = open('Maneskin - Beggin.mp3', 'rb')
            un = open('Panic! At The Disco - House of Memories.mp3', 'rb')
            um = open('Blind Channel - Dark Side.mp3', 'rb')
            uo = open('Maneskin - Lets Get It Started.mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_audio(call.message.chat.id, um)
            bot.send_audio(call.message.chat.id, uo)
            bot.send_message(call.message.chat.id, ms, reply_markup=btn1)
        if call.data == 'Электронная':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Подробнее", url="https://mp3party.net/genres/%D1%8D%D0%BB%D0%B5%D0%BA%D1%82%D1%80%D0%BE%D0%BD%D0%BD%D0%B0%D1%8F"))
            ms = 'Электронника'
            uu = open('Axel Thesleff - Bad Karma.mp3', 'rb')
            up = open('RYLLZ - Nemesis.mp3', 'rb')
            un = open('Tony Igy - Astronomia.mp3', 'rb')
            um = open('Furkan Soysal - Babylon.mp3', 'rb')
            uo = open('Teriyaki Boyz - Tokyo drift.mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_audio(call.message.chat.id, um)
            bot.send_audio(call.message.chat.id, uo)
            bot.send_message(call.message.chat.id, ms, reply_markup=btn1)
        if call.data == 'Поп':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Подробнее", url="https://mp3party.net/genres/pop?sort=pop"))
            ms = 'Поп'
            uu = open('Bishop Briggs - River.mp3', 'rb')
            up = open('NK - Elefante.mp3', 'rb')
            un = open('The Tech Thieves - Fake.mp3', 'rb')
            um = open('Elley Duhe - MIDDLE OF THE NIGHT.mp3', 'rb')
            uo = open('Carla Morrison - Disfruto.mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_audio(call.message.chat.id, um)
            bot.send_audio(call.message.chat.id, uo)
            photo = open('Rad.jpg', 'rb')
            bot.send_photo(call.message.chat.id, photo,ms, reply_markup=btn1)
        if call.data == 'Шансон':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Подробнее", url="https://mp3party.net/genres/shanson?sort=pop"))
            ms = 'Шансон)'
            uu = open('Фристайл - Ах, какая женщина.mp3', 'rb')
            up = open('Дмитрий Гревцев - А я еду домой.mp3', 'rb')
            un = open('Сталкер - песня из бара бандитов.mp3', 'rb')
            um = open('Арсен Шахунц - Девочка, стоп!.mp3', 'rb')
            uo = open('NЮ - Никто.mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_audio(call.message.chat.id, um)
            bot.send_audio(call.message.chat.id, uo)
            bot.send_message(call.message.chat.id, ms, reply_markup=btn1)
        if call.data == 'Казахстан':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Подробнее", url="https://mp3party.net/collection/populyarnye-kazahskie-pesni"))
            ms = 'Казахстан'
            uu = open('Raim & Artur ft. Zhenis - Дискотека из 90.mp3', 'rb')
            up = open('Raim & Artur - Самая вышка (OST Ia - Jenih).mp3', 'rb')
            un = open('Ерке Есмахан - Кайда.mp3', 'rb')
            um = open('Madi - Девочка из города Караганда.mp3', 'rb')
            uo = open('НАZИМА - Беги.mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_audio(call.message.chat.id, um)
            bot.send_audio(call.message.chat.id, uo)
            bot.send_message(call.message.chat.id, ms, reply_markup=btn1)
        if call.data == 'Орындаушылар':
            markup3 = types.InlineKeyboardMarkup(row_width=2)
            btn1 = types.InlineKeyboardButton('Скриптонит', callback_data='Скриптонит')
            btn2 = types.InlineKeyboardButton('Скиллет', callback_data='Скиллет')
            btn3 = types.InlineKeyboardButton('Imagine dragons', callback_data='Imagine dragons')
            btn4 = types.InlineKeyboardButton('Eminem', callback_data='Eminem')
            btn5 = types.InlineKeyboardButton('Баста', callback_data='Баста')
            btn6 = types.InlineKeyboardButton('Nirvana', callback_data='Nirvana')
            markup3.add(btn1, btn2, btn3, btn4, btn5, btn6)
            photo = open('Rad.jpg', 'rb')
            bot.send_photo(call.message.chat.id, photo, 'Сборка исполнителей, если нету то что вам нравится, можете написать мне, обязательно их добавим!', reply_markup=markup3)
        if call.data == 'Скриптонит':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Слушайте здесь выших любимых исполнителей здесь", url="https://mp3party.net/collection/%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%BD%D0%B8%D1%82"))
            ms = 'Скриптонит'
            uu = open('Скриптонит - Пацан.mp3', 'rb')
            up = open('Скриптонит - Положение.mp3', 'rb')
            un = open('Skriptonit feat. T-Fest - Lambada(Hype Up REMIX).mp3', 'rb')
            um = open('Скриптонит - Животные.mp3', 'rb')
            uo = open('Скриптонит - Интервью.mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_audio(call.message.chat.id, um)
            bot.send_audio(call.message.chat.id, uo)
            bot.send_message(call.message.chat.id, ms, reply_markup=btn1)
        if call.data == 'Скиллет':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Слушайте здесь выших любимых исполнителей здесь", url="https://eu.hitmotop.com/artist/1272?ysclid=lbidupeqmc618570524"))
            ms = 'Скиллет'
            uu = open('Skillet - Psycho In My Head.mp3', 'rb')
            up = open('Skillet - Hero.mp3', 'rb')
            un = open('Skillet_-_Monster.mp3', 'rb')
            um = open('Skillet - Legendary.mp3', 'rb')
            uo = open('Skillet - Beyond Incredible.mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_audio(call.message.chat.id, um)
            bot.send_audio(call.message.chat.id, uo)
            bot.send_message(call.message.chat.id, ms, reply_markup=btn1)
        if call.data == 'Imagine dragons':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Слушайте здесь выших любимых исполнителей здесь", url="https://mp3party.net/artist/836"))
            ms = 'Imagine dragons'
            uu = open('Imagine Dragons - Whatever It Takes.mp3', 'rb')
            up = open('Imagine Dragons - Its Time.mp3', 'rb')
            un = open('Imagine Dragons - believer.mp3', 'rb')
            um = open('Imagine Dragons - thunder.mp3', 'rb')
            uo = open('Imagine Dragons - Demons.mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_audio(call.message.chat.id, um)
            bot.send_audio(call.message.chat.id, uo)
            bot.send_message(call.message.chat.id, ms, reply_markup=btn1)
        if call.data == 'Eminem':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Слушайте здесь выших любимых исполнителей здесь", url="https://mp3party.net/artist/9"))
            ms = 'Eminem'
            uu = open('Eminem - Lose Your self.mp3', 'rb')
            up = open('Eminem - Not Afraid.mp3', 'rb')
            un = open('Eminem - Not Alike.mp3', 'rb')
            um = open('Eminem Dido - Stan.mp3', 'rb')
            uo = open('Eminem - The Real Slim Shady.mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_audio(call.message.chat.id, um)
            bot.send_audio(call.message.chat.id, uo)
            bot.send_message(call.message.chat.id, ms, reply_markup=btn1)
        if call.data == 'Баста':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Слушайте здесь выших любимых исполнителей здесь", url="https://mp3party.net/artist/902"))
            ms = 'Баста'
            uu = open('Баста - Сансара.mp3', 'rb')
            up = open('Баста - Выпускной.mp3', 'rb')
            un = open('Баста - Урбан.mp3', 'rb')
            um = open('Баста - Моя игра.mp3', 'rb')
            uo = open('Баста - Мама (Скажи мне мама, сколько стоит моя жизнь)..mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_audio(call.message.chat.id, um)
            bot.send_audio(call.message.chat.id, uo)
            bot.send_message(call.message.chat.id, ms, reply_markup=btn1)
        if call.data == 'Nirvana':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Слушайте здесь выших любимых исполнителей здесь", url="https://mp3party.net/artist/76"))
            ms = 'Nirvana'
            uu = open('Nirvana - Smells Like Teen Spirit.mp3', 'rb')
            up = open('Nirvana - Come As You Are.mp3', 'rb')
            un = open('Nirvana - Lithium.mp3', 'rb')
            um = open('Nirvana - Rape Me.mp3', 'rb')
            uo = open('Nirvana - About a Girl.mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_audio(call.message.chat.id, um)
            bot.send_audio(call.message.chat.id, uo)
            bot.send_message(call.message.chat.id, ms, reply_markup=btn1)
        if call.data == 'Басқалары':
            markup3 = types.InlineKeyboardMarkup(row_width=2)
            btn1 = types.InlineKeyboardButton('Ойындар', callback_data='Ойындар')
            btn2 = types.InlineKeyboardButton('ТикТок', callback_data='ТикТок')
            btn3 = types.InlineKeyboardButton('Аниме', callback_data='Аниме')
            btn4 = types.InlineKeyboardButton('Сайттар', callback_data='Сайттар')
            markup3.add(btn1, btn2, btn3, btn4)
            photo = open('Rad.jpg', 'rb')
            bot.send_photo(call.message.chat.id, photo, 'В прочее вы можете слушать разные песни или находить сайты и т.д. и т.п. И если хотите что то добавить пишите в личку', reply_markup=markup3)
            bot.send_message(call.message.chat.id, '<b>👉Telegram:</b> t.me/StalkerStalker41', parse_mode='html')
        if call.data == 'Ойындар':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Жақсы көретін орындаушыларынызды осында тынданыз", url="https://mp3party.net/genres/igrovoe"))
            ms = 'Ойындар'
            uu = open('GTA San Andreas - Main Theme.mp3', 'rb')
            up = open('Hyper - Spoiler.mp3', 'rb')
            un = open('TryHardNinja - Its Me.mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_message(call.message.chat.id, ms, reply_markup=btn1)
        if call.data == 'ТикТок':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Подробно", url="https://mp3party.net/genres/music-from-tik-tok"))
            ms = 'ТикТок'
            uu = open('Smokepurpp - Audi..mp3', 'rb')
            up = open('Сява - Без Повода.mp3', 'rb')
            un = open('Furkan Soysal - Babylon.mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_message(call.message.chat.id, ms, reply_markup=btn1)
        if call.data == 'Аниме':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Подробно", url="https://mp3party.net/genres/anime"))
            ms = 'Аниме'
            uu = open('Kenshi Yonezu - Kick Back.mp3', 'rb')
            up = open('Franz Ferdinand (Cyberpunk Edgerunners OP) - This fffire (Киберпанк Бегущие по краю аниме опенинг).mp3', 'rb')
            un = open('KANA-BOON - Torch of Liberty [Enen no Shouboutai Ni no Shou OP2].mp3', 'rb')
            bot.send_audio(call.message.chat.id, uu)
            bot.send_audio(call.message.chat.id, up)
            bot.send_audio(call.message.chat.id, un)
            bot.send_message(call.message.chat.id, ms, reply_markup=btn1)
        if call.data == 'Сайттар':
            btn1 = types.InlineKeyboardMarkup()
            btn2 = types.InlineKeyboardMarkup()
            btn3 = types.InlineKeyboardMarkup()
            btn4 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Өту", url="https://mp3party.net/"))
            btn2.add(types.InlineKeyboardButton("Өту", url="https://eu.hitmotop.com/"))
            btn3.add(types.InlineKeyboardButton("Өту", url="https://zaycev.net/"))
            btn4.add(types.InlineKeyboardButton("Өту", url="https://sefon.pro/"))
            bot.send_message(call.message.chat.id, "Mp3party, Жақсы және танымал сайт, мұнда сіз жақсы ремикстер мен ойындарды таба аласыз", reply_markup=btn1)
            bot.send_message(call.message.chat.id, 'Hitmo, Сондай ақ керемет ремикстері бар жақсы сайт', reply_markup=btn2)
            bot.send_message(call.message.chat.id, 'Zaycev_net, Мұнда сіз әртүрлі жинақтарды жүктей аласыз', reply_markup=btn3)
            bot.send_message(call.message.chat.id, 'Sefon, Сондай ақ кез келген нәрсені тыңдауға болатын ең жақсы сайттардың бірі', reply_markup=btn4)
        if call.data == 'Жаңалықтар':
            btn1 = types.InlineKeyboardMarkup()
            btn1.add(types.InlineKeyboardButton("Подробно", url="https://mp3party.net/genres/anime"))
            ms = 'Жаңалықтар әзірше жоқ' \
                 'Жаңалықтар пайда болса сізге сообщение жібереміз!'
            btn1.add(types.InlineKeyboardButton("Өту", url="https://mp3party.net/"))


bot.polling(none_stop=True)
